index.html
Thank you for the tutorial. Helped a lot. i added my thank you message to the html file.
=> Added thank you message from Dewan

index.html
Just added some feedback to index.html file
=> Added feedback

index.html
I added a sample message into index.html
=> Added sample message

index.html
=> Added message from Mieszko

index.html
i added a file in appreciation of the nice gesture w3schools has enabled everyone to learn programming for free
=> added a new message to show appreciation

index.html
I add my message to guest book!
=> Adding RomaRobot Message!

index.html
Added my small banner to thank you for tutorial. Thanks!
=> index.html : Added thanks message at the very bottom of "user messages" section.

index.html
=> Add my user message

index.html
=> add some lines with text

index.html
=> Everything for you

index.html
=> message by onepunch man

index.html
- Try forking w3 schools repository
=> Add Message to index.html

index.html
Just adding my bit :)
If you see this, I love you and everything you do.
Keep being you
=> Added my message to the list! Besos de un medio-Argentino medio-Irlandes!

index.html
=> Tutorial practice 

index.html
I added a message to index.html
=> Added Manu message to index.html

index.html
Modified the index.html adding a little section thanking w3schools and sending greetings to everyone out there.
=> Modified the index.html

index.html
I just did this in a class as an activity, if you want to accept it cool, but if you don't that's fine too, Thanks for undertanding!
=> a genshin player

index.html
Hi W3school, the book is on the table. I love this tutorial, thanks!!! 😘😘😘
=> Mensagem W3school

index.html
=> Mesagem W3school

index.html
My message of Sombrio, Santa Catarina from Brazil
=> My_Version

index.html
I added my own comment for the guest book.
=> Update with changes from Joe

index.html
=> mensagem adicionada

index.html
I have learn a lot from this tutorial, so a thank message is necessary.
=> Add a thank you message to index.html.

index.html
I Added My Name And Some Useful Quotes in index.html
=> A new Quote And Self Details are added to the index.html

index.html
=> nova versão

index.html
Hi this is a text from Brazil.
=> Lucas L. T. Version

index.html
=> mensagem do guilherme

index.html
=> nova alteração

index.html
here is the truest message from brazil
=> W3schools Murilo

index.html
=> w3schoolsM

index.html
Hi, i left my message from Brazil
=> versão ana

index.html
=> w3schoolsD

index.html
=> Mensagem do Ruan

index.html
Hi, W3Schools!
Thanks a lot for this tutorial!
Congrats!
=> Joedio's message

index.html
Hello W3school community, I'm learning git on your site!
I would be happy if you add me in html code without any problem!
:)
=> I added my message, and where I'm from, and a little html code :)

index.html
I removed the small modification I did on someone else code
=> message from congo

index.html
A phrase often used by finnish when Finland is mentioned.
=> Added a finnish way to say hello

index.html
Added a simple greeting to index.html
=> Added greeting to index.html

index.html
I just added my message in a div element. hope to see it on the page :)
=> new message added from MMP

index.html
I added  a message from my side to the code
=> Added a message from Ryyan

index.html
this adds a new comment to the index,html file he he
=> Added a new comment for me

index.html
A new div block is added by me indicating my name and date of insertion.. I have put appropriate comments before and after the block.
=> A new div block is added by Musthak Ahamed

index.html
Thank you so much for this tutorial. I love W3.
=> Leave a message for W3 ^^

index.html
I added my message to the index file.
=> leaving my message

index.html
Added a message near to the end of the page, just for demo purpose
=> added thankfull message from Anniel

index.html
Added a new div element and a message.
=> Added a new div element

index.html
I added a funny quote by Jim Carey, and fixed a spelling mistake in 1 of the Albert Einstein quotes.
=> Added a quote by Jim Carey, and fixed spelling error

README.md, index.html
=> first commit first-fork

index.html
=> Added code. wiwr

index.html
I add my message in index.html (in guestbook)
=> Changed to serve as a public guestbook test

index.html
finished git and Github tutorial . interesting and helpful
=> update index.html with my experence

index.html
=> Adding a comment to index.html

index.html
Modified index.html file to include my message.
=> Added Message from George Kioko

index.html
added a quote thanking the authors of this git tutorial
=> added a qoute under budi-tech

index.html
added new div in index which says hello in Georgian :)
=> added first georgian text :)

index.html
Added a div element with a message of encouragement to all self taught developers out there
=> added message from Oling Emmanuel Benjamin

index.html
Hi! Please approve my pull request!  Thanks!
=> 20230907_tes_1

index.html
Some people copied my code including my div id.
=> :bug: fix (Update index.html): differentiate id of objects

index.html
I only modified the index.html file adding my quote.
I was able to achieve this and send the Pull request thanks to my discipline to get here in the course.
I am immensely grateful to you. Since this course has taught me a lot.
=> Agregamos al index.html nuestra cita favorita

index.html
testing contributing to another's project
=> testing contributing to another's project

index.html
I added my greetins to the w3schools comunity
=> Added a message to the end at the page

index.html
I create my own message "Love w3school and school 21 (Todd1s)" for community in index.html
=> Create message from Todd1s

index.html
I added an encouraging verse from the Scriptures in index.html
=> message from Dwayne

index.html
I added my comment in latest line of index.html file
=> Add my comment to index.html file

index.html
I add some div in index page .
=> Change in index page..

index.html
I practice all git commands that are tech in this course.
=> Add my name umair

index.html
Add custom message to w3schools github page
=> Testing Github fork

index.html
Added one line with a welcome message
=> Added a line with a message

index.html
Adding some changes as instructed form w3shool Git tutorial.
=> Added my name and my country to index.html

index.html
Added some text to index.html, just like everybody else :)
=> Just some text added by Ciprian, Thank you for the course guys.

index.html
this is my message for W3 messageboard
=> this is a pumpkin seeds message

index.html
I added my greeting to index.html to thank you for the tutorial.
=> Modified index.html added greeting

index.html
I have applied the lessons learned from w3schools.
=> change by githubuser0101

index.html
Thank you all for this great course. I added a message in the index file
=> Added thankyou message

index.html
I have added user massage to index.html. Thank you for the tutorial.
=> Add user massage from adep from Indonesia

index.html
I added a message to Index.html to reflect changes for Shridhar.
=> Added message for Shridhar

index.html
Thank you all for this interesting tutorial
=> Added a little thanks message in index.html

index.html
Added some greeting text - "Hello from Uzbekistan"
=> Added greeting text

index.html
added a personal greeting massage to the page
=> added a massage

index.html
added text and styles for the message according to the comments in the code. only index.html.
=> Added new message by lanshead

index.html
added a new comment from oostasolutions
=>  Added a new comment

index.html
I added a thank you message to index.html.
=> Added message from salesa

index.html
I updated index.html to include my entry in the guestbook.
=> Changed to add my entry in the guestbook

index.html
I wrote my greetings in index.html. Hopefully i can master this course and other courses in W3Schools.
=> write some greetings in index.html

index.html
=> I have added my guest log Shivani

index.html
=> dino-nejasmic w3schools-test

index.html
Do this like it says in the course. And I am adding my comment in the bottom of the index.html
Big Thanks! I hope I can pay w3school after I getting the job. I am sure I'll find the way how I can do this
=> Adding my wish and continue learning

index.html
I've added my thanks to index.html webpage
=> Added personal message to index.html

index.html
I've added a quote from Ken Thompson.
=> Please accept my new message.

index.html
please accept my changes i am testing fork repository
=> New di added

index.html
I made sure to make full use of my imagination
=> Update index.html (creatively)

index.html
I added a line of message at the end of the file.
=> Updated index.html with a new line of message.

index.html
Added a personal message from myself, Matas. to the W3Schools community! :)
=> Added personal message

index.html
I added my message in index.html file
=> Added my message in index.html file

index.html
I added a new line in index.html
=> Added my message in index.html

index.html
Added my little section for practicing
=> Just another commit

index.html
Added my comment during the tutorial
=> Added comment to index.html

index.html
I added, removed and updated file to serve as public guest book.
=> Changed to serve as public guest book

index.html
=> message from cdlv added

index.html
Thanks to your excellent tutorial, I have create my first pull request and added a greeting towards the end of index.html
=> Added a greeting

index.html
added my quotes and motivation words to other developers
=> munashedev message

index.html
I added some contents to the html
=> Gift Amachree

index.html
Added message for revision purpose by [Tahseen Ahmad Bhat](https://www.linkedin.com/in/tahseen-ahmad-bhat-b77204246/)
=> One more contribution

index.html
I created a div showing my message for everyone
=> Send positive message to everyone

index.html
I added a message that says hi.
=> Adding a message in index.html

index.html
I added my hello message to page
=> Added a piece of HTML

index.html
A new message from me, SmithPH
Thank you for the tutorial!
=> input message from SmithPH

index.html
=> message from lmao

index.html
I created  a message for the users.
=> Pull request from w3schools learner, Misbah

index.html
Hello, It is my contribution. It was either this or a spongebob meme...
Thanks to w3shools team ❤
=> It is my contribution

index.html
hi i've just added my message .
=> Changing the index.html file 

index.html
=> Add hello message.

index.html
Added my part for the GitHub tutorial
=> GitHub tutorial

index.html
i made some changes in index.html file.
=> added a div with a sentence

index.html
I added a message in the index.html file as a contribution to this awesome project!
=> A message from Yassine Essaouri

index.html
Added a little piece of HTML, CSS and JS as a guest message.
=> My guest message added

index.html
I have changd index.html to just add my message too :)
=> Amirali has changes index.html

index.html
I added an introductory message and thank you line
=> Thank you w3school

index.html
Modified the index.html by adding a comment
=> Wrote a comment

index.html
I have added a some text in index.html file.
=> Added a message in index.html

index.html
I removed, added and updated files to make this able to serve as a public guess book. Future changes should be only to index.html
=> Change to serve as a public guessbook

index.html
I have added another thanking message to the main html file.
=> Added thanking message

index.html
I added a thanking message in the index.html file.
=> Added a message by luiscostas

index.html
Just added my touch to the file
=> Added a thankyou message

index.html
I followed the guidelines in the `readme.md`.
I have added a message to the board.
I will be very happy if you accept these code changes and publish my message.
Thank you so much for the git & GitHub course.
=> Am glad I took this class. Thanks w3schools

index.html
addes to served as a guest book just in index.html file
=> Pull request for update index.html

index.html
Added some html code I liked with my job description, name , and GitHub username !
=> Added my own greeting to the index.html page

index.html
i added my message for the git tutorial
=> added my owm message!

index.html
=> Adaugare comentariu de la mihaibu1201

index.html
=> FireRiver Added Message

index.html
Added my message to the messageboard in index.html
=> adding message to the board

index.html
updated index.html and a message is added.
=> Updated index.html with a message

index.html
i have added my message by adding my introduction and my feedback for this  public guestbook project.
=> Message from Farhan Reza

index.html
=> Added my own 2 cents

index.html
I just added a section with a title, a paragraph and a small picture in the index.html
=> Changed to serve as a public guestbook 

index.html
Added a welcome message with some image and styling
=> Create a welcome message

index.html
Changed based on Git course on w3schools
=> Update index.html with a-anjomi message

index.html
I added one very simple message between the indicated comments.
=> Added guessbook message to index.html

index.html
I added the changes as part of my git and GitHub tutorial
=> changes to original code

index.html
=> Update index.html with fsfrani

README.md, index.html
=> Updated readme file

index.html
I have added my message to this index file. I know my fork is 77 behind due to delays and didn't know I could sync forks using GitHub. Anyways thanks W3Schools once again for such innovative gift at the end of this tutorial.
=> Added my (AdySaz3658F) message to index.html

index.html
=> Just Getting Git

index.html
added a message at the bottom of the file
=> New Fork Test added comment

index.html
Just added a line of greeting message.
=> Updated index.html with greeting message.

index.html
I added a simple Greek quote in the index.html file.
=> added a greek quote to index.html

index.html
I just added my entry to the end of the guestbook.
=> Added message from Ivan, Belarus

index.html
I add my message that follows by the guestbook guideline.
=> Add my message to guestbook

index.html
Line 10398 :  <p style="font-family: monospace; text-transform: uppercase; font-style: italic;">Hello World from Liège, Belgium.</p>
=> Added <p> to index.html.

index.html
I have added my quote.
Yours truly,
Yelyzaveta
=> Liza have added the message

index.html
I added a new message to inspire all members in the index.html file.
=> New message added from ajehangirk

index.html
=> signed by curious

index.html
I added "Jiawei's message" in index.html
=> add jiawei's part

index.html
Added message from Stasuke to file
=> New message from Stasuke

index.html
I have added my message into index.html.
=> Added my message.

index.html
=> Message from Italy!

index.html
I added an appreciation comment in the index.html
=> Added changes in index.html

index.html
=> Hello from Czech Republic

README.md, index.html
Adding personal message from Worm. Nothing was changed in README
=> Adding personal message

index.html
Here goes a new message in the guestbook, from me!
=> feat: add new message

index.html
Added a small phrase into the guest book to thank you for the tutorial. Thanks!
=> Added my tag here

index.html
Added greeting to public guestbook only in index.html
=> Updated index.html with greeting for public guestbook

index.html
Added my experience of learning from W3 schools.
=> My first commit in W3 schools from git

index.html
Just add Francisco's message in the index.html file
=> Add message from Francisco

index.html
Hi, i have added my profile card for collaboration in w3school GitHub learning.
=> Message form MD from Nepal

README.md, index.html
I added a new text at line 167 to say thank you for your helpful tutorial <3
=> Add a new text in index.html file 

index.html
I added my own message to the guestbook.
=> added my own message to the guestbook

index.html
I've added a message to the index.html file, which says "Thank you"
=> The message from Egypt has been added to the index.html file !

index.html
Message from Samir for the W3schools Tutorial Guestbook
=> message from Samir

index.html
I added my connect to the end of index.html to basically sign the tutorial guestbook. Please review and approve.
=> Blair Wagner updated index.html in fork tutorial

index.html
Hello! Thank you for this awesome tutorial in W3C! 
I'm submitting my message to the public guestbook.
Cheers,
Jean
=> Inserted my message to the public guestbook

index.html
I added a hello message to index.html!
=> Adding a hello message to index.html

index.html
I edited the index.html to add my message to the public w3school web.
=> I added a message as a guest, thank You!

index.html
CCC: this is just some simple try
=> CCC's pull request

index.html
I added my message to this page.
=> Emmanuel's Message

README.md, index.html
I added some comments to the readme.md file.
=> Updated readme for Pull Request

index.html
Added a new message as part of the w3 schools Git tutorial lessons
=> RJ added a new message

index.html
I added a guest entry for Lukas Eppacher
=> Changes to serve as a guest author

index.html
In this digital realm where bits and bytes collide, I assure you, every word I utter is as real as bugs in production code. Yes, brace yourselves, for this disclaimer is the unicorn in the land of GitHub repositories – it's both real and fantastical. All claims made herein are as solid as a rock, or at least as solid as my commitment to hitting the 'merge' button before the heat death of the universe. While it's true that I have been accused of being a code connoisseur who only drinks from the cup of your brilliance, fear not! I assure you, my intentions are as pure as a freshly initialized variable.
Yes, indeed, let it be known far and wide that this masterpiece of wit and wisdom was also conjured forth by none other than GPT itself. As surreal as it may sound, this message bears the …
=> chatgpt made message

index.html
I just add a greeting from Argentina. Nice to be learning with you guys! Thanks a lot for your content.
=> add greeting from Argentina

index.html
=> Inserted message by Bharat

index.html
Added "Jerry Message" Block. Styles only apply to selfmade "Jerry" Ids.
=> Added Jerry Message

index.html
Simply add a thank you message here.
=> Add thank you message By Chin Guang

index.html
I added a short message thanking W3Schools.
=> Added Craig's message

index.html
=> New message

index.html
=> added message from shruthik

index.html
This uses SVG codes to create a smiley face. I also added a paragraph tag with 2 words.
=> Adding a happy face and a positive comment.

index.html
I updated and added my greetings in index.html
=> Added my greetings in index.html

index.html
Hello, I'm learning how to contribute to the open projects & I've added one small text
=> written text in index.html

index.html
Hi, i added a new line in the code,please review and try to include
=> added a new line

index.html
added some messages to index.html. tank you for this!
=> Added Some Message

index.html
I add a text to index.html to contribute to this repository
=> Changes to test git contribute

index.html
added my message for the world to see :)
=> Update with message from Dingo#666

index.html
Updated the text "Thankyou" to "Thank you" in index.html
=> Added Some Changes to index.html

index.html
=> Message from Bryanik

index.html
I added my message to the Guestbook 😄
=> Added my note to the Guestbook

index.html
I only added a line "Fiuh! Finally I am here. It's a long journey."
=> Updated index.html with a line from me

index.html
I updated the index.html file to add a message for anyone who read the book.
=> change to serve as public guestbook

index.html
I added a message at the end of the page.
=> add message from Guillaume

index.html
I am learning how to use Git and GitHub and I am grateful to w3school for their amazing tutorials. Therefore I added some kind words to their guest book.
=> LenaSemenova added her thanks to the guest book

index.html
I am learning GitHub Fork with w3schools.
I added my signatory comment to index.html and I want to see the results of my practice.
=> learning how to fork in GitHub with w3schools

index.html
I have enjoyed this tutorial!  Thank you!
=> Added message from Marty in index.html

index.html
Thank you W3schools , Ebrahim Gamal
=> I thanked this awesome website

index.html
Added motivational message from a book I am currently reading to index.html
=> Added motivational message to index.html

index.html
This is my contribution to the **_Guestbook for w3schools.com Git tutorial_**. 
I struggled a bit with this chapter "Git Contribute", because I made various mistakes before I could finally reach this point.
Thank you for your work and your amazing tutorials.
=> Updated index.html with marecemarto message

index.html
I added my message and reduced a few lines of tags in the head css (nothing important)
=> adicionado minha mensagem-Fabricio

.gitignore, index.html
I have written a message as a learner to say hello world
=> some lines are added to the index.html file 

index.html
I added my name to the public guestbook with some minor styling
=> Updated index.html with a new log entry

index.html
Updating index.html by adding my name MUGISHA from Rwanda
=> Updating index.html by adding my name MUGISHA from Rwanda

index.html
I added a new section to index.html for my personal message on the guest book.
=> Added new message to index.html

index.html
I have added a sample message to create a pull request
=> added a sample message

index.html
=> added messsage

index.html
Hello!
Just adding my guestbook message to the list of messages as part of learning Git!
Cheers!
=> Add guestbook message from reiyua

index.html
Thanks for this awesome tutorial
=> leave my first message on w3school-test repo

index.html
just practicing git and github
=> message from vishal singh

index.html
Testing out git fork and git clone.
=> message from Ned

index.html
I have changed index file as you mentioned thank you
=> index file changed

index.html
I have edit index file that I can also contribute on github.
=> this is for s3chool study

index.html
I added my personal thank you note to the index.html file.
=> Added my thank you note

index.html
I added a quote to index.html in the place it was supposed to fit into
=> added message to index.html, mdaszuta

index.html
Added an inspirational message on the virtues of simplicity in index.html.
=> Added inspirational message.

README.md, index.html
Correcting incorrect placement of Guestbook message from README.md to index.html
=> Guestbook message moved from README.md to index.html

index.html
=> Added message from Nour

index.html
Mandar made changes to index.html .
=> GitHub Contribution by Mandar

index.html
I added my message to the page. thanks
=> message added by shariq yousuf

index.html
added a image of w3 school and my message.
=> added my message to the guest book

index.html
This is a little h1 i added on the page (this is my fingerprints)
=> I LET MY FINGERPRINTS ON THE W3SCHOOLS PAGE

index.html
Adding my message to the message book!
=> Message book

index.html
=> msg added to Guest Book

index.html
Added my message at the end of the <body> in index.html
=> Made changes to the index.html file

index.html
- Added a message in index.html file
=> Add message in index.html

index.html
I added my message at the end of the html file. 1 "div" 1 "head" and 1 "paragraph".
=> CheMoneb message added

index.html
=> Test 08:12

index.html
I have added a thank you note in index.html file.
=> Added thank you note git add index.html

index.html
I have added a thank you note to w3schools on their well-structured git course.
=> Added a thank you note to w3schools

index.html
Added vote of thanks to W3Schools for the great work done in teaching the world about Web development
=> Rian's input to the Git Tutorial Guestbook

index.html
I added a greeting and refixed a fail from me in the index.html
=> Change to serve as a public guest book

index.html
Add a new comment to index.html
=> Add a new comment to index.html

index.html
Add my details, comment and change font type.
=> Add my details 

index.html
The message is about my favorite soccer team, thanks for all the content of W3S.
=> Added my msg on html file

index.html
=> Added my message to the page.

index.html
I have edited some message in index.html
=> Edit Message in index.html

index.html
Modified the index.html with a course review message.
=> Added a message in index.html from Cristi

index.html
=> New index.html

index.html
i added a div and added my infomation in that div
=> Feat: add div with my info

index.html
A small token of appreciation for Your great work.
=> New comment in guestbook.

index.html
7 new row in the index.html file.
=> new commit from xeon kivy

index.html
Added an entry from Homer Simpson
=> Homer Simpson

index.html
Muito obrigado pelo tutorial de vocês, bom demais vcs são fera!
=> Obrigado w3Schools

index.html
=> Hi from me

index.html
I added my own note to be publish on public guestbook of this tutorial
=> Updated index.html. Added note

index.html
=> added a thanks  message

index.html
=> changes from egypt

index.html
This pull request adds a thank you message to the index file, expressing gratitude to w3schools for their support and resources.
=> add thank you message

index.html
I contributed to this project by adding a message thanking this beautiful website !
=> Added a message from Adem Diari

index.html
Learning Git and GitHub. I just added greetings to practice purpose.
=> Hector's signature

index.html
corrections from before on not altering original content ;)
=> updated message from Greece

index.html
Really loving the git tutorial here: https://www.w3schools.com/git/git_remote_send_pull_request.asp?remote=github. Thanks team!
=> Made a change from middle earth

index.html
I added my section on the html file only thanks.
=> HI, everyone I'm mohamed from Sudan

index.html
Kindly add my code to the main repo
=> Kindly add my code to the main repo

index.html
I added my name and a big heart of love, greeting w3schools
=> my contribution on github repository created by w3schools

index.html
added a message to index.html at the end.
=> Message from Happy

index.html
I just added a few words of gratitude from me to you in the guestbook.
=> I added my signature to the guestbook

index.html
I added and updated the index.html with my message
=> Added message from Deep

index.html
I added a guestbook entry after following the W3Schools tutorial on Git and GitHub.
=> added a guestbook entry

index.html
I added a spooky message to celebrate Halloween in July.
=> I added a message.

index.html
Thanks for the great tutorial!
=> Added message of gratitude to guestbook.

index.html
Added user message from ahal22mail to the index.html
=> Update index.html added user message from ahal22mail

index.html
Added personal message to the guestbook. Future changes will only be made to index.html.
=> Added message -Rebecca Smal- to index.html

index.html
=> add greeting to index.html

index.html
Hello ! I have just add my section message in index.html. In message, "Misaotra" mean thank in malagasy.
=> ADD message from Randriantsoa Manantena

index.html
I added my message at the end of the page.
=> Added message from.. me.. Farnood

index.html
=> added new msg

index.html
add a text message to the end of the page
=> Add a new message 

index.html
=> Thank you message for w3

index.html
=> added 123.DEV

index.html
Adde my message from line 11325 to 11333
=> Add my message 

index.html
=> firs contribute

index.html
Added a message from one man in Ukraine
=> Added message from Murat YEsimbietov

index.html
Added a new entry (100–106) from shushtain to index.html
=> Added a new entry from shushtain to index.html

index.html
this commit from mohamed ahmed
=> this commit from mohamed ahmed

index.html
I removed, added and updated files to make this able to serve as a public guest book. Future changes should be only to index.html.
=> Changes to serve as public gust book.

index.html
Understood the article and edited the index file by adding some content in it and commited with my message
=> Added my message Tegh Singh

index.html
I only added 4 lines at the bottom of the html page with my little message
=> My contribution to the w3 github test page

index.html
=> added user message by Jouona

index.html
I added a message to the guest book
=> Changed to serve as my own public guest book

index.html
I added two comments in index.html
=> updated index.html with two comments

index.html
Added a message at the end of the file.
=> Adding a message

index.html
Adding changes in index.html file
=> adding the changes in index.html file

index.html
Added my comment to index.html per the tutorial. :-)
=> Added my comment to index.html

index.html
I modified the index.html part to make my change
=> update the index.html

index.html
I have added a div section with a message for w3schools
=> Message by Issac

index.html
Message added accordingly to the w3schools git-tutorial, thanks for your doing :D
=> Message by arpegx

index.html
=> Massage added to index.html file

index.html
I added a div block, saying hi, to index.html
=> Add greetings to index.html

index.html
Not much to say, I'm just following the tutorial.
=> Added a new line to index.html

index.html
this is just to my contribution
=> add name praveen india

index.html
Updated with Atakan from Turkey's greeting.
=> Updated with my message in the guestbook.

index.html
i edited the index.html i added a new h2 tag where i introduced myself in single line code
=> introduced myself with other learners

index.html
Se crea un mensaje de saludo al final del Index.html
=> Mensaje From Venezuela

index.html
I have wrote my text. Hope, it will be shown in the page of w3school.
=> added my message happily

index.html
Greetings message from Cali Colombia
=> Greetings from Colombia

index.html
New student learning git and github. Added new message to guest book.
=> Added new message - Sean from Texas, US

index.html
=> Commit de prueba

index.html
Change in index.html. Insert a personal message.
=> Changed to serve as a guestbook

index.html
I add a new comment in the beginning of permissioned section
=> feat: add comment from Anna in index.html

index.html
Shared a simple routine that can lead to nurture your coding skills and also left a quote.
=> Added my message to the community

index.html
I added a block of code and I had put my name in there
=> nice greetings FABIAN

index.html
I added a small phrase of my favorite singer: Cancerbero. Future changes should be only to index.html
=> added a personal text

index.html
Thank you for teaching me. It will be really helpful for my career.
=> Added my line for thanks

index.html
I added a funny knowhow about camels in the index.html file
=> Added a funny knowhow

index.html
I added my feedback on the course below Michael's message
=> Added my feedback for the git and Github course

index.html
I updated index.html to add a thanks from Carl block.
=> Added Carl from Boston block

index.html
added my guestbook enty to the guestbook
=> New Guestbook Entry

index.html
Placed my message withim the relevant section as requested
=> Changed the position of my message

index.html
Added thsls message at index.html
=> Add thsls message

index.html
Mayowa added his heartfelt appreciation message to W3Schools.
=> Mayowa added his appreciation message to W3Schools

index.html
Added my quote for the tutorial challenge.
I made a variation of Fabián´s quote because I loved it.
=> Added my quote

index.html
Add my message on the last portion of the body tag.
=> Added Neil message

index.html
Correct spelling on my message from greatful to grateful
=> Correct spelling on my message

index.html
Zuma, a tech newbie, added his appreciation message to the index.html file.
=> Zuma added his heartfelt appreciation message to W3Schools

README.md, index.html
Thank you for the exercise!!
Small mistake i make that I didnt sync the original repository to my fork first, which makes my index.html conflict when trying to do a pull request.
Future change should be only in index.html
=> Adding small comment after fixing conflict with master file on index.html

index.html
- Added my message to the index.html file
- Message inserted as the last message of the file
- Basic CSS applied to the HTML elements
=> update index.html with message

index.html
Nothing interesting only a simple quote from SW...
Nice Git and GitHub course anyway <3
=> Hello there!

index.html
Adding a message to W3Schools' Git tutorial. It's quite amazing how you guys have set this up, just to teach us! Thanks!
Changed index.html
=> Added thank-you message for the tutorial!

index.html
Greetings added to the guestbook.
=> Greetings added to the guestbook

index.html
=> I just added a 2 line html element describing what i am learning

index.html
just added an anna2 block message
=> add anna2 message

index.html
Added hello message to index.html
=> Message from Husam

index.html
add new hello message into index.html
=> Hello from Juan

index.html
by adding my name and a few paragraphs and divs at the end of the page
=> changed index.html file

index.html
In the index.html I added a comment showing the start and the end of my message. Between the comments is a div with an internal CSS style along a paragraph, two headers (h2) and images showing a gratitude towards w3schools.com web page.
=> Added a message from Silverayer

index.html
Added hello from LeDuyPhuong - Viet Nam
=> Added hello from LeDuyPhuong - Viet Nam

index.html
=> changes from adam

index.html
i am adding a new comment on w3 github public page.
=> added my comment on w3 git page

index.html
I added my message to the index.html file :).
=> Added message from Mickael

index.html
yo admins, please respond.
yo do the admins reply?
btw do you in any case understand brainrot...if you do please merge, it will be so not fanum tax.
=> i am being being saitama right now

index.html
Added one message in the end of index.html
=> Hello from KCHR, Russia

index.html
I added my name to the end of the guest book.
=> BogdanBigBoss added his message

index.html
I've added a personal card on the board in index.html.
=> Added messages to the board

index.html
I made some change to the file index.html which is my greeting to everyone.
=> greeting from Thangbodoiqua

index.html
I would like to sign the guestbook by adding the changes I've made to my fork to the upsteam.
=> Added DenverChess to the GuestBook

index.html
Added a sentence of entry to the guestbook with my message thanking W3 schools.
=> Added my entry to guestbook

index.html
I have added a message to your code for testing and cloning purpses
=> Changes made to file

index.html
I have added my Hello text at the end of the index.html file.
=> Changes from Raghuraj

index.html
Added a new message to the guest book.
=> Message from Pebble94464

index.html
I have added content in the specified area in index.html file
=> added additional content in index.html

index.html
=> hello from lebron

index.html
=> Change guestbook

index.html
i add some meme from indonesia
=> changed to serve as a public guestboook

index.html
i am nizam, i modified index.html with adding my feedback hope you accept this
=> i am nizam, i modified index.html with adding my feedback hope you accept this

index.html
Added a new message from myself. 
Previous request contained conflicts; previous request has been closed.
=> Added message from myself (Ryan H.)

index.html
only added my massage in the right place in index.html
=> added my massage to the board ! thank you !

index.html
I have written a message for w3schools in the index.html file to learn the forking process.
=> Modified the index.html file to add a message for w3schools

index.html
Testing out git fork, git clone, and creating a pull request to contribute to an open-source project.
=> Added Vincent user message

index.html
i added a friendly message to the index.html :)
=>  adding my friendly message to index.html

index.html
I added and update files to make this able to serve as a public guest book. Future changes should be only to index.html
=> Updated index.html add message

index.html
I´ve followed the w3Schools tutorial, please acept my pull request. Thanks in advance.
=> Mensaje Nacho UTEZ 2024

index.html
following the w3schools git fork tutorial, and happy to contribute with the guess page
=> Mensaje Hello World from mexico

index.html
=> añadí mi nombre

index.html
Hello I have followed the steps of the tutorial W3school
=> Mensaje Hassiel Utez

index.html
I´ve followed the w3schools tutotial, please accept my pull request. Thanks in advance.
He seguido el tutorial de pull request
=> h1 agregado

index.html
i 've followed the steps mentioned on w3school
=> se agrego un comentario

index.html
I added one line into de index file following the w3school tutorial.
The meesage says "agregue mensaje de una linea".
=> Agregacion de 1 linea en index.html

index.html
I´ve followed the w3school tutorial, please acept my pull request. Thanks in advance.
=> Mensaje de Aylin UTEZ 2024

index.html
=> create a server Update index.html

index.html
Working through the w3schools git tutorial and created a fork from test repo, added message to index.html and committed to my fork.
=> Added message from James,UK.

index.html
Hello I am follow your tutorial in W3. I would like to be part of your site!!!
=> Message from UTEZ 2024

index.html
Hello guys! I'm sending my thanks! This is a great tutorial. Thank you for helping me.
=> adding thank you

index.html
As per tutorial, please approve this pull request :)
=> tutorial pull request

index.html
=> added Thankyou note

index.html
=> Greeting message added

index.html
Added gratitude message from user LePandolfo, using css tags from W3chool/css
=> Added gratitude message

index.html
acho que coloquei muitos dados! mas podem reduzir se for necessário, obrigado
=> Update index.html with my bios thanks all

index.html
added an entry in the guestbook
=> added guestbook

index.html
Added an entry to the guestbook
=> Added guestbook entry

index.html
added an entry in the guestbook
=> added new user

index.html
Added something to the GuestBook
=> added this TAG

index.html
I have just practiced my learning strategy.
=> this is zahid from pakistan.

index.html
I wrote a few html lines on my introduction to the index.html
=> input my message to index.html

index.html
Signing into the Git Guestbook
=> Signing into the Git Guestbook

index.html
=> Ernest Ampem's message of gratitude to w3schools

index.html
Quote added from Mae West. Greetings from Kenya
=> Added a quote from Mae West

index.html
=> Added a message from Janne

index.html
I added my cheers in the bottom of `index.html` file.
=> Add cheers to index.html

index.html
added entry for user "jondz" at the bottom
=> add index entry

index.html
I have edited the index.html file to include my message. Thank you.
=> Add message to index.html from Khoa Nguyen

index.html
New greetings message from NK has been added to the guestbook
=> Added new greetings message to the guestbook

index.html
=> Add a new message and fixed missing symbol on previous in guest book

index.html
Added a greeting to index.html
=> Ibim message

index.html
Added a div tag to index.html with some p tags embedded.
=> Updated index.html with a couple of lines

index.html
Added my thanks message to the html
=> Added my message inside html

index.html
Hello,
please pull my new message of today.
Thank you
=> w3s: add my new comment

index.html
Added a thank you message to index.html
=> Updated index.html with thank you message

index.html
Added my html message and edited heading tag as well in the index.html file
=> Added message and edited heading tag misnomer 

index.html
I have added my message on line 223 to 226
=> my commit to index.html

index.html
Commit for W3S from REFRAZ1 <3
=> Commit for W3S from REFRAZ1 <3

README.md, index.html
I removed the line from README.md and put them in index.html as instructed.
=> Added a thank you line.

index.html
I add a hello message to the index.html. All the best.
=> Modify the index.html with a nice hello message

index.html
Added comment in the end of *index.html*. Thanks W3Schools. I learned so mutch!
=> Added comment by Marcelo Hüning, SC-BR.

index.html
added a user message to the guestbook
=> signed the guestbook

index.html
Adding my thoughts and begin with the learning.
Regards,
=> 1st commit by AK

index.html
Added message to index.html
Thank you w3!
=> Updated index.html with message

index.html
My thanks message to the tutorial is added to the file.
=> Added my message from India

index.html
=> Updated a thank message, joseph from Somalia

index.html
I added a message to greet my fellow w3schools learner.
=> added a greeting message for lynpacis

.gitignore, index.html
updated the index.html after completing the w3school tutorial.
=> added name

index.html
Added a section in index.html to demonstrate the usage of fork and clone in Git/GitHub.
=> Add message from Samson

index.html
=> I added message

index.html
Adding this information: "<h1>Finally, I have figured out how fork works. I am very happy!</h1> ".
=> adding Bo message.

index.html
I added my own text to the index.html file.
=> omar ramirez agregó su contribucion al proyecto

index.html
I added a message in the end of index.html as a token of appreciation for creating a page on git & github for learning.
=> first change on w3

index.html
=> index.html with new addition

index.html
Added one h3 text "I'm stucking here, but it seems ok..."  in index.html
=> added h3 text in index.html

index.html
I just added my personal message to the index.HTML page saying thanks to w3schools for the good work and help.
=> I updated the index.HTML file with my message.

index.html
I have added my thanks message.
And removed some dead image links that stick the page loading.
=> Add my message, and remove broken images url

index.html
added my message into the index.html file (I used IcyJuicyBob as the name because this is my other account and I prefer that name to be listed) - there is 7 commits to this because I didn't type my code/message right multiple times
=> Adding IcyJuicyBob's Message to index.html

index.html
Hi from Barcelona! Thanks for the tutorial, I added a missatge with thanks :)
=> Sergio TXT

index.html
I just added a message from me to the repository
=> Adding message from me

index.html
i had to close the old pull request, so here is a new one
=> Added my message again

index.html
=> added greetings from anas to index.html

index.html
Hi, I'm excited to add my nickname to your website.
=> chore: add greetings from spyde3rx

index.html
Changed message background color scheme
=> Updated Ragnaslav's message in index.html

index.html
=> Added TXW4326 message

index.html
I have added a message at the top of the user's  messages
=> message from shakti-kc

index.html
I just added a simple message on the index page
=> Changes done by Waqas

index.html
Added a message under comment thanking w3schools for the good work
=> added message to index

index.html
=> git tutorial guestbook

index.html
I added greeting to index.html
=> updated public guestbook

index.html
I added a block leaving a message from me.
=> Leaved a message on Guestbook

index.html
=> Added message from me, Lomantik

index.html
Big thanks to W3Schools for their amazing Git tutorials!
=> Aravind R Krishnan added a message !

index.html, test.txt
I've added some hello messages to "index.html"
=> Practice for pull request from w3school tutorials

index.html
Thanks for the awesome tutorial.
=> Added My Message Tile

index.html
I updated the index.html file to include my comment in the Git Tutorial Guestbook.
=> Changed the index.html

index.html
Added a message to index.html. Thank you again for the wonderful tutorials!
=> Added new message for w3schools tutorials, great job

index.html
I added my thank you message at the end of index.html
=> added my thank you message at the end of index.html

index.html
Added my thank you message to W3School!
=> Updated index.html with thank-you section

index.html
=> added a message:)

index.html
I added a message for the W3Schools team to congratulate them for the good work being done to train people in the vast world of technology.
=> Zachariah Agbenorto added a message for the W3Schools team

index.html
=> added a note from bill-mortimer

index.html
=> Updated messages in index.html & README.md

index.html
Added a new message for fork testing. And thank you! w3schools.
=> Add a new message for testing fork lesson

index.html
Added a message at the bottom of the index file as instructed in the w3schools Git & GitHub tutorial :)
=> Added a message by Midget in index.html

.gitignore, index.html
Updated index.html according to the guidelines.
=> Add thank you from Leslie Williamson

index.html
I added and updated files to make this able to serve as a public guest book. Future changes should be only to index.html
=> Updated index.html with a quote

index.html
I signed public guestbook with personal message.
=> Added message from RomanaDiana

index.html
I added a comment in index.html
=> Message from Tomek - Poland

README.md
I added test comment on README.md file
=> test comment was added to README.md

README.md
Reverts w3schools-test/w3schools-test.github.io#4016
=> Revert "test comment was added to README.md"

index.html
I added my message in the index.html to follow the tutorial properly, the first ones were not done correctly ...
=> adding my message

index.html
Added a comment of mine in the index
=> add Emanuele's comment

index.html
=> Add MannyMartinez Message

README.md, index.html
updated only index.html
(hope it's good even if 3 commits)
=> message in index

index.html
I Just added a beautiful div with a message to thank w3school for all the teachings
=> Add message from Stephane Sonkin

index.html
Added code in the message section
=> Added message from sss122

index.html
=> adding my section to index

.ipynb_checkpoints/index-checkpoint.html
I added a  message to show my appreciation to the W3school  and fixed a small CSS bug of a guy
=> A small contribution to the public guestbook

index.html
I`ve added a message "Hello from Ukraine" in the file index.html. I hope I did it right though because I just copied the code structure of the person below.
=> Add greetings from Ukraine

index.html
I added a message expressing my gratitude on this tutorial. Then I added the color white to line 232.
=> Oluwamayowa sending gratitude from Nigeria

index.html
My contribution to the guestbook following this awesome Git guide.
=> My message to w3schools-test

index.html
updating index.html with thank you msg from Bob
=> updating index.html with thank you msg from Bob

index.html
i edited index.html only on this guestbook by w3schools
=> changed-by-khan

index.html
I have added a message to index.html.
=> Hello from Angel at Florida

index.html
contribute for learning purpose.  git is awesome
=> contribute for learning purpose

index.html
I added an appreciation message
=> Added an appreciation message

index.html
Added a new guestbook message.
=> Update index.html with new guestbook message

index.html
Adds a small div to the end of the Guestbook!
=> Adds my personal message to the Guestbook

.ipynb_checkpoints/index-checkpoint.html
Expressed the gratitude to w3schools.
=> Add message - Prabhas Avvri
