- index.html
added a message for training purposes
> Add new message

- index.html
> a message from e.e.cummings

- index.html
Another Quote has been added to the index.html, written by Linus Torvalds.
> A new Quote added by Linus Torvalds

- index.html
I added a new french quote to the index.html file.
> New citation added from France

- index.html
I add my message at the index.html file.
> A change was do it

- index.html
> index.html has been updated

- index.html
I have added my entry to the guestbook as per the W3Schools tutorial.
> add my details to the html file

- index.html
Added a saying in the index file hope it'll be appeoved.
> Added a saying in the index.html

- index.html
I have added my line o f quote in index.html that can viewed by everyone on W3school Git tutorial.
> Added my quote in index.html

- index.html
> add my own example message

- index.html
> lleks added message

- index.html
> added a quote from me in index.html

- index.html
I learned how to use git and github following your tutorial. I have added my quote to the index.html page
> I added my own quote to the github tutorial guestbook on index.html 

- index.html
Hello my name is Luiz Felipe
I would like to include my comment in your index file, to show my students how the Pull Request works.
> Incluir meu comentário

- index.html
Just going trough tutorial.... so here you go.
> index.html edit: adding my quote

- index.html
Hi, I hope you have a good day
I added a quotes from Kent Beck.
> add KentBeck Quotes

- index.html
My comment was modified in index.html file
> lleks comment was modified

- index.html
I added a message to page index.html
> I added a message to page

- index.html
I update index.html with text "Hello, I'm come from Viet Nam"
> update index.html with text

- README.md
- index.html
I'm not sure if this kind of contribution is allowed, but I noticed a few writing errors in the README file and fixed them.
Edit: I also added a message to the index.html file.
> Fixed a couple of writing errors in the README file

- index.html
I added a new comment container.
> New comment by Gabit

- index.html
> New message added to index.html

- index.html
i have added my message to the guestbook (index.html) per the instructions in the readme and the GitHub send pull request tutorial.
> Added my message to the Guestbook

- index.html
> Added my content

- index.html
Added a thank you message for the tutorial
> Thank you message for GitHub Pull Request tutorial

- index.html
I added a small div block like other contributors
> github pull request test from souleymane

- index.html
I added and updated the index.html file to make it serve as a public guestbook
> Changed to serve as a public guestbook

- index.html
I updated file & added my username & a message in the repository AKA public guest book
> Message added by user ssakib4050

- index.html
Los cambios realizados implementan un cubo y una frase seguida del nombre del autor, que es mi persona. Los estilos CSS fueron agregados en los mismos bloques de código HTML y de esta manera respetar los pasos establecidos en el README.md.
> Cambios realizados en el archivo index.html

- index.html
> add vaishnav

- index.html
adding my name and my message in "insert message below here", thank you for the tutorial.
> adding my name and my message in "insert message below here"

- index.html
thank you w3school team. Your content is excellent.
> Added personal message. Eduardo Mejias Avila

- index.html
The svg stuff is only there for the cool flames that I learned how to make thanks to w3s as well :D
> added my message :) Daniel M.

- index.html
I included a div section on index.html : Your courses are amazing. Can you make a tutorial on data structures and algorithms?
> Comment by Michael Mbajwa

- index.html
added "HI" in spanish in the message section
> Added new message

- index.html
I'm learning git from W3Schools and now I'm learning about pull requests.
> Added my tekst - micun

- index.html
Hello W3schools  team please accepte this pull request .
> thank you message

- index.html
- new.txt
I added my message to index file, with bold text.
> I added my message

- index.html
Adding a div tag to index.html file
> adding a div tag to index.html

- index.html
I have added a personal message as part of W3Schools Git Contribute tutorial
> added personal thank you message

- index.html
> message added

- index.html
Hi My name is eigkivz from thailand am learning git repo from you W3School. Thank so much for grad knowledge.
> commit from  thailand

- index.html
I just added my own message to w3schools. grateful for the free awesome content they give to us.
> Added my own message in index.html file

- index.html
I and some messages on index.html I hope you approve it...and thank you so much, you helped me alot
> send message

- index.html
Express my gratitude for w3schools :100:
> Add message

- index.html
added a text paragraph to index.html to complete w3school Git tutorial
> added a paragraph to index.html

- index.html
Thanks a lot for teaching GitHub !! and I also picked up some html while writing the message : )
> Added my message for the Guestbook

- index.html
The only change i've made is a div container with my message and author in index.html.
> Added public message for W3Schools

- index.html
> K-pi public guestbook

- index.html
add an important life lesson quote.
> Add an important Quote

- index.html
> added Rahul Pulagam from India user message at end

- index.html
hey, i am learning git . So ,I hope this pull request is accepted to see the repository changes
> change by khangdovan

- index.html
> Added a message

- index.html
User message added to guestbook.
> Added user message

- index.html
I'm working on W3Schools git tutorial and really appreciate your efforts.
> Muhammad Nabeel From Egypt
> A new message added

- index.html
I have updated index.html with a new message.
> Updated index.html with a new message

- index.html
Added a message to Guestbook :)
> HobbyMath Added Message

- index.html
Added my message to  Guestbook.
> Add My Message

- index.html
I added a message in Portuguese to the Guestbook. The translation is "W3Schools, thank you so much for the Git/Github tutorial, I learned a lot"
> Added message to Guestbook

- index.html
added new message to index.html
> Updated index.html with new message

- index.html
Resolved merge conflict and updated index.html with my message.
> Updated index.html with my message

- index.html
I added my message to index.html
> added my message

- index.html
added my message in the index.html file for testing my pull request
> added some changes

- index.html
> Greetings from my local git repo bros

- README.md
I deleted, added and modify something in READ.md files for pull request testing.
> Modified for pull

- index.html
just add my message like the others :)
> added message on index.html

- index.html
> contribute w3s

- index.html
Added a HTML block with a message to index.htlm
> changes to index.htlm

- index.html
Just another message from a w3s student.
> new message added by rg

- index.html
Just another message from a w3schools student.
> new message added by JD HINCAMAN

- index.html
Thanks, w3school for providing such a wonderful platform.
> Add Quote and Name

- index.html
Just added my addition to guestbook.
> Added my few lines of text!

- index.html
I wrote a new message for a public guest book.
> Just new message

- index.html
> adding comment from Rahim

- index.html
> primer cambio en local

- index.html
I only added one block of code to add a new entry to the guest book in index.html
I touch nothing else.
Thanks, have a nice day
> signed guest book

- index.html
~Paid courses~
***W3schools Free documentation*** ✔
> Gratitude from India for your documentations

- index.html
> it is my update

- index.html
> letting a message to say the tutorial was useful, congrats!

- index.html
Great tutorial!
I just followed the instructions of it!
Thank you!
> Added Evangelos Meintasis text at the index.html

- index.html
hello, i add my message to you, hope you approve.
> add a message to you

- index.html
I added a message in the guest book. Only updated 1 file which is index.html.
> Updated index for guest message

- index.html
> Another line of Thanks:)

- index.html
I just write a message in index.html
> nulis pesan di index.html

- index.html
added line in comment section of html file
> Added comment to html file

- index.html
Hello, this is the repository with my comment added, 
please accept it.
Thank you W3Schools. 😊
> Comment added from Artmen

- index.html
I added my message to the index.html guestbook. Thanks for your excellent tutorial!
> Greetings From Ireland!

- index.html
Added few lines at the appropriate line number
> Small greetings to W3Schools and fellow learners

- index.html
I added my line of a message!
Thank you w3schools!!!
> New message from Indonesia

- index.html
> Name update

- index.html
I only added my comments to the last of user messages
> Added my comments to public guestbook

- index.html
I added a message to the w3schools gh-page
> added my own message to w3schools gh-page

- index.html
I add a greetings from Belarus in index.html
> Add greetings from Belarus

- index.html
I added my comment to index.html to serve as public guestbook
> I added my contribution as public guestbook

- index.html
I added a note with some paragraphs. I'm so thankful for all W3schools's contributions. 
Happy thanksgiving to everyone.
> Happy Thanksgiving to all W3schoolers

- index.html
> KN Comments on 26Nov2021 - what am i doing on black friday

- index.html
I have added my comment to the guesbook. Thanks for this exercise.
> Added my comment to the guestbook

- index.html
i have edited the index.html file to insert my appreciations to w3schools for teaching me how to use git and github
> added my apreciations to w3schools

- index.html
I add new message in index.html
> Added new message to  index.html

- index.html
> Added my greeting to the guestbook.

- index.html
I'm adding some messages in Spanish for the people not so familiar with English.
> Cambiando w3school

- index.html
I added my greetings in index.html
> Added greeting to the index.html

- index.html
I add more my ideas in index.html
> Change more to index.html

- index.html
I have added my message to index.html.
> Index updated

- index.html
index.html file is edited to add a message and creating a pull request.
> Message added from the dcodingkid

- index.html
> add message and update index.html 

- index.html
I added my quote to the index.html.
> Updated index.html with Ekoorits quote

- index.html
I added my name to the guest book. Thanks for the awesome in depth tutorial! Git felt nearly unapproachable for me and now I feel really comfortable with it.
> added my name to the guest book in index.html

- index.html
> Added a greeting from Max

- README.md
- index.html
> make message

- index.html
I added my own message to test out all that I have learned about git from your tutorial and have fixed another persons inline styles as they had "text-color" instead of just "color" and unless VS code is lying to me I don't think it worked.
> Added my own message and fixed someone elses inline css

- index.html
Hi  I just added message from me to index.html
> Modified by Marek

- index.html
> Risqi's update

- index.html
This is a task being part of the **Tutorial**.
> Updated index.htlm with thanks div

- index.html
I left a message for the guestbook
> Ptaxan addes new message to guestbook

- index.html
> adding kushal message regards of w3s

- index.html
Hi, i am from bangladesh 
thank you w3school to teach our genaration for free
> Added a new gestBook message

- index.html
Have reverted the changes made and send a new message in the specified div tag
> Reverted the changes and added a new message - thank you

- index.html
I added a div to express my satisfaction with learning git.
> Added a div

- index.html
My first contribution to w3schools-test repo.
> My message was added to w3schools-test

- index.html
I added my second message and do my practise.
> added my second message

- index.html
Pull request for GIT Tutorial 
Git GitHub Send Pull Request
https://www.w3schools.com/git/git_remote_send_pull_request.asp?remote=github
> Pull Test 20220120

- index.html
I added a comment on the git tutorial.
> Compliment to Git Tutorial

- index.html
I updated some files to make this able to serve as a public guest book. Future changes should be only to index.html
> Added my message(Change to serve as a public guestbook)

- index.html
I Added my Contribution to the index.html File.
> Adding my contribution

- index.html
Hey! i have added a message to your repository
> Added my message to the repo of w3schools

- index.html
> Left a message in index.html

- index.html
Added a new message in the index.html file.
> added message

- index.html
I edited the index.html file to add my message.
> Added Tharinda's message

- index.html
I have add a greeting message in the html file. Thank you W3Schools for this wonderful opportunity!
> Changed to server as a public guestbook

- index.html
> New messagge from Italy

- index.html
I added a new message and commited, then fixed indent in my own message and commited again.
> Added a new message and fixed indent

- index.html
I am learing and added a message
> love from bangladesh

- index.html
> Added my greeting

- index.html
> Added my personal message

- index.html
> Added my hello at the end of index.html

- index.html
> Ishak Fork Test

- index.html
> Chamget to serve as a public guestbook

- index.html
I added some HTML and CSS with my own message to the public guestbook!
> I added my own message to the public guestbook!

- index.html
git class, thanks.  
Added a thank you text.
> Adicionado uma mensagem de agradecimento

- index.html
> chansocheat sok change

- index.html
I added and update files to make this able to serve as a public guest book
> Change to serve as a public guestbook

- index.html
Thanks for all the tutorials 💯 
Here is my Git fork try
Liu
> My contibution L

- index.html
> my participation

- index.html
> add yaser change

- index.html
> COngratulazioni da Firenze - Italy

- index.html
Made an update to the index file to add my own contribution for the guest book
> Added my little piece to the guest book index file

- index.html
Added my thank you message at the bottom of the guestbook
> added my own message in guestbook

- index.html
I added my message in the index.html file
> created thank you message

- index.html
Love from W3Schools's student.
> My messege to the community

- index.html
In solidarity with Ukraine.
Thank you for your great Git tutorial!
> Added a message to the guestbook

- index.html
I have added my comments with my name.
Thanks for this platform and encourages us to contribute.
> updated index.html - added my comments with name

- index.html
Changed index to learn how to use forks
> Changing for tomorrow

- index.html
> I just added my name as link pointed to my fb id and todays date

- index.html
I add my message from Buenos Aires, Argentina.
> Changes in index.html file

- index.html
> Quiviro leaves a message to the world

- index.html
It looks good!!! Please approve ^^~
> my new message

- index.html
I've added my message at the end of the guestbook.
> New message in the guestbook

- index.html
started my journey from w3schools.com
creating a pull request for the first time
> @shaiksamad was here

- index.html
just add a line in the index.html , insert my html tag in messages section
> testing fork

- index.html
Modified index.html: added greetings from Fabio
Merged with upstream and re-committed
> Modified index.html: addedd greetings from Fabio

- index.html
Thank you message added by Tushar
> Thank you message added by Tushar

- index.html
> Change an index.html file

- index.html
Thank you for the opportunity.
> Adding Ribobo's message

- index.html
I just leave a message on the webpage(index.html)
> leave message on index html file

- index.html
Adds a new user message from me in index.html.
> Adds a new user message

- index.html
> My regards added!

- index.html
Adding a review in guest book.
> Alexandro changes

- index.html
> Guestbook Post added

- index.html
Hi! I included my piece of code. Hope you like it! :)
> added bugahontas message

- index.html
I'm Mohammad Hosein And I added some line for w3schools.
I changed index.html.
Lines : 1817-1873
> Mohammad Hosein added  some lines from 1817-1873

- index.html
I added a new message to the guest book.
> Added new message to guestbook

- index.html
> Leave a trace

- index.html
Thank you W3Schools for your great contribution! 
I have added my regards in index.html
> Gobi's Regards

- index.html
Following the tutorial and just adding in my two cents.
> Adding comment to commit

- index.html
my first pull request with the help of **w3school**
Thanks, w3school
> Added my name to the public guestbook

- index.html
Adding a quote from Elon musk.
the only file changed is index.html.
> Elon musk quote

- index.html
> Added row for fork

- index.html
Changes to serve as a public gueast book
> indexfile updated

- index.html
I changed the position of the thank you line I created previously
> changed the position of the thank you line created 

- index.html
Added my name to register presence.
> Added my name to register presence

- index.html
I added a message and a blinking name with a five line javascript.
> Added D_captainkenya section message.

- index.html
I added my thank you message to the top of the page, Thanks for everything guys
> I added my thank you message

- index.html
I edited the index.html and added a new block of html codes.
> Udated index.html with a message from Yusuff

- index.html
Left a message on the Git Tutorial Guestbook page under Josephzal
> Added my message to guestbook

- index.html
> humendra here

- index.html
Just added several code in index.html
> Added a new message from Kei

- index.html
I have included a 'Thank You' message in the index.html file
> Message included in index.html

- index.html
> Update W3 Schools

- index.html
Please add my greetings entry :)
> I was there too

- index.html
I added my guestbook entry to index.html.
> Added new guestbook entry

- index.html
Added a new message to index.html. Thanks.
> Updated index.html with a new msg

- index.html
Thank you for all the great tutorials! I just wanted to add a note of appreciation.
> Added Richard's message

- index.html
Updated the file using the GitHub tutorial on W3Schools.com!
> Message from Vancouver!

- index.html
I add a quote in the index.html file
> Change to served as a public guestbook

- index.html
I have added to commit with my guest log. Kindly Add Team w3School.
Love from India.
> Changed my log in Public guest book

- index.html
Added my message to index.html while following the git tutorial
> Added a message to index.html

- index.html
hi there from w3schools i kindly ask you to merge my request :)
> added a new message

- index.html
Added a a thank you note at the end of the index.html file in a div
> added a thank you note to index.html

- index.html
I added in code,update file index.html
> New code add

- index.html
(note the extra </div> on line 2317 was added to close that user's div, it was left open and wrapping the following divs)
> Added entry to message board

- index.html
My guest book entry is just before the  comment, lines 2336 to 2340. I kept it very simple to not override any existent CSS rule.
> added a new message as another Kevin to index.html

- index.html
> Added a new entry to the guestbook

- index.html
I added another div at lines 635-646 with a thank-you message for all the great guides.
> Added a thank you div on lines 635-646

- index.html
a thank you note for this great tutorial. tried different tutorials, but this the one that help me understand Git and Github. Thanks.
> add new message for w3schools.com tutorial

- index.html
Hi guys, thanks from learing us Git.
> Hello from Romania

- index.html
> Added a few lines of thanks.

- index.html
Updated index.html with a new entry in the guestbook.
> Added index.html guestbook entry.

- index.html
I updated the index.html file with my details
> Updated the Git Tutorial Guestbook with my details

- index.html
I added a div element having my message for public in index.html.
Nothing removed from index.html
Nothing replaced in index.html
Changes were only made to index.html
> Aakash Dinkar made this commit to add a public message

- index.html
I added a card containing my message to w3schools
> Ali Rihan added his message

- index.html
I have added a message from my end on the index.html page to serve as a guestbook.
> Changed in index.html to serve as guestbook

- index.html
Added a few lines at the bottom of index.html
> Added an insignificant quote in index.html

- index.html
> Changed index.html in fork

- index.html
Changed to serve as a public questbook
> Changed to serve as a public questbook

- index.html
Hello. I am learning git with w3 tutorial. I send you  a pubic request. Thanks.
> cambios en index.hmtl

- README.md
- index.html
I updated index.html. Thank you for your tutorial!
> Thank you for your tutorial!

- index.html
> Updated message saying Thank you for the tutorial!

- index.html
Added a guest book entry for BB
> Add BB guest entry

- index.html
Future changes should be only to index.html
> commit from Vietnam

- index.html
Updated index.html file with a quote to test fork and merge to a remote repo. 
I hope the request will be accepted.
> Updated index file with a quote to test fork and merge

- index.html
Thanks a lot for the tutorial. Very straight forward.
> Added a thank you message to w3schools for the tutorial

- index.html
Thank you very much for the great Resources!!!
I added my thankful message to index.html
> Added my message to index.html

- index.html
added a thank-you comment to see if it works:)
> added my part to the comment area

- index.html
Please review my PR, Hoping to see soon my code live on https://w3schools-test.github.io/
> commit from raju-kumar-s, bangalore, india!

- index.html
modified index.html to thank w3schools
> thanks w3schools

- index.html
I added a div section to the Index.html file that contains my name.  Practicing Git with w3schools is fun
> Added by Manger George

- index.html
> New Messaage from Rajendra Kumawat India

- index.html
Added a short message for the public guestbook
> Message added by MFord

- index.html
thanks for the lesson, i know a lot about git and github
> added message thank for tutorial to index.html

- index.html
Added a message between line 2706-2710
> W3SGitTutorial

- index.html
I test Git Contribute feature of w3school git tutorial. I added div tag in index.html.
> Test git contribute feature

- index.html
I'm following your tutorial, so I would like to leave my message:)
> Added thank message

- index.html
Update index.html file, sending my message
> Contribution of Israel Rojas

- index.html
Added a message to the public guest book in index.html
> Message from the Netherlands

- index.html
Added message to index.html to practice as mentioned in the section "GitHub Send Pull Request" tutorial
> Added message to index.html

- index.html
> Changes Made

- index.html
Tried to have GitHub copilot write this for me when following the tutorial.
> Added a thank you to index.html

- index.html
> Add new user message

- index.html
Updated index.html in order to leave my message there. You can ignore this if you want since i basically copied the HTML code of another person in the guestbook. Thanks for the speedy course!
> Guestbook Update

- index.html
I created my message to your page!
> Created KienDuy's message to share with the community

- index.html
I updated the index.html by adding my message to the public guest book.
> Added new message to the index.html

- index.html
> message from SagharMax

- index.html
I added a line in index.html file
> added line to index.html

- index.html
I add a new comment about this tutorial.
> add new comment

- index.html
> Added my line

- index.html
I added h1 and p to index.html
> Updated index.html 

- README.md
- index.html
Only a new message was added to a guestbook
> changes to index.htmp

- index.html
I added my opinion about w3schools
> I just added my opinion.

- index.html
I've changed index.html in order to pass your tutorial. It was fun. Hope you'd enjoy the message.
> Vlad added a message to index

- index.html
New message added in index html document
> Change document

- index.html
Updated index.html with a quote
> Updated index.html. Added a  Quote

- index.html
Test fork, add some message in index.html
> add some message in index.html

- index.html
I love you guys, have a nice day!
> Leaving a new message

- index.html
I forked, clone and made changes to the index.html file by adding few lines of codes.
> Just added few lines in index.html

- index.html
I added a message for W3school after going through the git tutorial. I found it so amazing I had to participate in this exercise.
> Message From Daniel Kubong

- index.html
hey w3schools , thanks a lot for your great tutorial
i added a new message here and hope to help some people
> Updated with new line

- index.html
I added to the public guest book. Thank you.
> Updated index.html by van2jazz

- index.html
I wanted to a positive recommendation. 
Keep up the good work w3Schools.
- Kingsley Omon-Edo
> Add a testimonial message from Kingsley

- README.md
- index.html
I added html elements containing my comment and name
> Changed to serve as public guestbook

- index.html
> added info

- index.html
Updated index.html to include a message from NYC
> Added a message from NYC

- index.html
> Added my contribution message

- index.html
I added my message in the line 2789. The message is about how thankful I am for the free courses you offered. I can't afford any certificates yet, but I really learned a lot in this website. Thank you.
> I added my own comment to the page.

- index.html
I added a new message to index.html
> This is my contrubution to w3 schools

- index.html
My message to the w3schools guestbook..
> Added a message to the index.html guestbook from Luis Pereira

- index.html
This is my first contribution to the github. I shared my thinkin to the coding society.
> first contribution to github

- index.html
I'll update some couple of line the start line no. 3065 . In this lines i try to show my little bit of my skill and learn to how VCS how works. I'll put the snapshot of output.
Thank you w3school .
> Add on show case as public GuestBook 

- index.html
I updated the html file and added my name and appreciation message
> Owzbi Appreciation

- index.html
Added my appreciation message.
> HBO appreciates W3Schools.

- index.html
> My message added

- index.html
I added my thanks message to the index.html file.
> Added message to index.html.

- index.html
I added new message to thank you all of you for created an interesting tutorial about Git and GitHub
> Added new message 

- index.html
added my own comment in the guest book
> Changes to index.html for guest book

- index.html
Thanks for all the great tutorials!
> Added greeting from Sweden!

- index.html
I updated the index.html, and put my message there.
> Update from BRAZIL

- index.html
Just finished up git lessons, added thanks to your guest book.
> Sergio's thanks to w3

- index.html
Learning github PR from w3schools has been fun all the way
> Fajmayor from Nigeria added his name section

- index.html
add comment on guest book in index.html
> add comment on guest book

- index.html
Thanks for helping me understand Git and GitHub!
> I added my thing to the index.html

- index.html
It looks wonderful, just ctrl+f Brioche150
> added my how to centre div message

- index.html
Updated page for w3schools' repository.
> Updated from mhusnucelik

- index.html
Just add another message from Viet Nam, UIT K15
> Add new message from Thien Nhan

- index.html
Just added a message as was instructed in the tutorial.
> A message to W3Schools

- index.html
Leaving some words in index.html~
> Changes to index.html

- index.html
> Message from Johanka added

- index.html
> With love from Ghana

- index.html
>  Added a message from Sepehr

- index.html
Update index.html with new message to thanks the W3School
> Update index.html to leave a message

- index.html
this is a good tutorial i like it very much
> Add my code

- index.html
Added thank you note to index.html
> Added thank you note to index.html

- index.html
I think this time is the right one :+1:
> Added a nice message

- index.html
i add my message to index.html to be shown in the guestbook and i talked about addin flutter tutorial.
> update index.html with my message

- index.html
Hello W3schools!
At first thank you for you test project in github.
The second is I commit two time because the first one is mistake that made it by me.
Please approve the second commit that it's name is ( Respect from AFG ) please.
Kind Regard 
Mansoor Alamyar
Front-end Developer
> A great quotation for Developers

- index.html
I added my own message, thank every W3schools Tutorialls contributer for everthing ! : ) 👍
> Added HZW Message

- index.html
Just a title in index.html changed as test
> Updated index.html as test change

- index.html
> Repo Fork Learning

- index.html
> Added message from random person

- index.html
> A small change

- index.html
I have added a comment in the index.html file
> Added message index.html (test fork command)

- index.html
Left a thank you note in index.html
> Updated index.html - DarkoSasanski

- index.html
I wrote a simple massage in index.html to see if I managed to configure correctly everything.
> Appreciation message in the 'Leave a message' section

- index.html
> Add Marie's message to index.html

- index.html
changeed to server as a public guestbook!!
> changeed to server as a public guestbook

- index.html
I added new guest talk at index.html file
> update index.html file

- index.html
I wrote my message in the index.html, thanks for all.
> Added my message for w3schools

- index.html
Added a line at the bottom of index.html under the comment "Added message from Texas"
> Added message from Texas

- index.html
I updated the index.html file, added my contribution/message
> Contribution from Stephen on w3school Git tutorial

- index.html
> My fork changes!

- index.html
Added a thank you message in the specified area :D
> Added a thank you message

- index.html
added  a message for community
> added a message for contribution

- index.html
> My changes for guestbook

- index.html
#My Contribution
This is my contribution to w3schools as part of the pull request exercise.
I added a few lines with a message to encourage everybody!
> Contributed to w3schools-test

- index.html
I added my personal message to index.html
> Updated index.html with personal message

- README.md
- index.html
Inserted message in index.html file.
> Message in guestbook

- index.html
Added a few lines at index.html with gratitude message.
> New message with gratitude

- index.html
I edited the index.html by creating a div tag. Inside which I added the quote.
> Added a famous quote of Albert Einstein in index.html

- index.html
Hi w3schools, I want to thank you for teaching me.
> Studying and practicing from Mexico

- index.html
This is my first open-source contribution, I've added a quote of mine. Thanks!
> contributing by updating index.html

- index.html
> message from kiran motkan

- index.html
I have added a phrase to index.html.
> Comment from Sominski

- index.html
Hello,
I've included a message on the index.html to be published on the public guest book.
> Including message from Ralph

- index.html
Added a new message at the end for this awesome tutorial!
> Added new message to the guestbook at the end

- index.html
I added my message to the index.html file.
> I added a my message in the index.html file

- index.html
> added message by rahul k

- index.html
> This Pull Request features my greetings and thankfulness to your amazing team 👍
> Include my salutions

- index.html
I added my message in the index.html
> Added my message to the public guestbook

- index.html
I added my message for guestbook.
> changed index file

- index.html
i have just added a line in the index.html for demonstration purpose .
> adding a new line by jaber zakik from morocco

- index.html
I have added myself into the guestbook!
> Added my self

- index.html
I have added my message to index.html
> Added ws message to index.html

- index.html
> Add new text in index.html

- index.html
I added some new lines in the proper place in the index.html file
> Updated index.html by ofirl

- index.html
Changed Index.html and added my self.
> message added by ANUBHAV

- index.html
i added new text to index.html. thank you for the tutorials
> added text to html

- index.html
I added my message only to index.html
> Added my thankful message.

- index.html
I have left a message, please add it to your website
> New line in index.html

- index.html
Thanks for your tutorial. As an international student, I'm struggling with my master's study and kinda feel depressed about everything. This place is just like a public diary where I can share my secrets and thoughts, thank you so much for building this.
> Add a message from Yifan

- index.html
> Added my Hello

- index.html
I simply added a line just to see how PR works in github.
> a line changed

- index.html
I added a message to index.html to thank the w3schools team for the great lessons.
> Thank you message.

- index.html
I changed index.html, added a new line in which I express my thoughts on w3schools.
> Changed index.html by adding my thoughts

- index.html
I left my comment, thanks!
Alejandro Gasca
> Greeting added

- index.html
I added the content to serve public guest book. Future changes should be only in index.html
> Added Notes by AMN

- index.html
I added a new file to index.html as a part of the GitHub tutorial on https://www.w3schools.com/
> added new paragraph

- index.html
I greeted w3schools for presenting git tutorials in good manner
> Ameer from India at 16/11/2022

- index.html
would you don't mind if i could add this text on your website ? thanks
> added some text to html by Erfan-ram

- index.html
> added new line i dont know if this is right

- index.html
> agregando mensaje

- index.html
Changed index file as explained in the tutorial.
> Changes based on public tutorial

- index.html
> add quotes from Albert Einstein into index.html

- index.html
This is me learning git again, dusting off some cobwebs, as well as learning some new tidbits of intricacies. Maybe I'll find a career I'm more interested in.  Thanks W3.
> Coding starter-off-er

- index.html
I add a message to thank the GitHub staff and W3School staff.
> message from Vietnam

- index.html
I am following git tutorial on w3schools and added a new message in index.html
> added new message to guestbook wall

- index.html
I added a new message to the guestbook.
> Message added from Marcio, Brazil

- index.html
I have added a quote in the index.html file
> Quote added

- index.html
Thank you for a great tutorial
> New message added, thank you!

- index.html
> Update from DEVOWFS

- README.md
- index.html
I have modified index.html file to add thanks message to w3school
> New message added

- index.html
Added my contribution message
Marvelous Innocent
From Abia State, Nigeria.
> My commit message

- index.html
I would like to contribute with a new message
> Adding a new message from Mexico

- index.html
Add a Thank You Msg to W3schools from Egypt!
> Adding Ayman Msg

- index.html
I added my greetings to your index.html file.
> Added greetings from Piotr

- index.html
I added a line in index.html file.
> Nima changed index file.

- index.html
I add a thank message in chinese, With a nice colored card in the index.html, at the bottom of the page.
> Message From Ireland

- index.html
I have added a mesage from Alan Phillips
Great Tutorial
> Added message from Alan Phillips

- index.html
Thank you W3 School for this amazing tutorial - Imad ZR from Morocco
> Add a new comment by Imad ZR

- index.html
> Message from Skill Rox

- index.html
> update the css of my comment

- index.html
I expressed my appreciation to w3schools for in-depth teaching and included my name as a list of contributors
> Expressed gratitude

- index.html
your are the best. i hope my text be inserted!💖
> wrote some text to contribute in this interesting course.

- index.html
i would like to say thank you a lot 
i added a message to index.html
> adding a message from morocco

- index.html
leaving my journey for my future self
> yeah leavin message

- index.html
Added my personal entry message to the guest book with inline styling.
> Add personal entry message to index.html

- index.html
Updated index.html with my personal message thanking w3schools for this amazing Git course!
> Added my personal message to the mix

- index.html
I added some notes that will be great for me!Thanks!
> index deyisildi ve commit olunur

- index.html
A left my message to W3Schools
> Message from bealfredo

- index.html
Thanks! I was just adding a <p>Hello!!</p>
> Added just a <p> with the words "Hello"

- index.html
I have added my personal message to the index.html file.
Thank you for making this guide, and many others.
> Added my personal message to index.html

- index.html
"thanks for this tutorial" was added as a new  message
>  a new message was added

- index.html
Changes made to index.html as "Great tutorial and learnt a lot about github - Kausik"
> Change to index.html

- index.html
> updated html message 

- index.html
I added some code that is for suggesting my changes to a different repository
> using fork to suggest my changes to a different repository

- index.html
> changes added - newly added

- index.html
I added a block to the end of the index.html file as part of completing the "GitHub Send Pull Request" chapter of w3schools Git tutorial.
> PWN 2023/02/06 commit changes to index.html

- index.html
Modified index.html to include my contribution from line 4749 to line 4755
> Commit from Ved, India!

- index.html
New div is added to the index page containing single paragraph
> new div is added

- README.md
- index.html
I added a comment saying hi at the end. Running the w3schools tutorial
> Changes for forking test

- index.html
Thanks for the content. Left a  message.
> Updated index.html to add a message

- index.html
This time just added my message in index.html file.
> Added line by KV

- index.html
learning git  : added a new line in index.html file from local repo and push to remote.
> Added a new line in index.html

- index.html
I added a stylesheet link to https://www.w3schools.com/lib/w3-colors-2017.css and wrote a message in the guestbook
> Message from Sandrine

- index.html
I have added my comment to index.html file. Please consider merging it. Thank you.
> Added my comment -PT(BD)

- index.html
Thank you message from Mark Szente, Budapest, Hungary
> Thank you message from Mark Szente, Budapest, Hungary

- index.html
> changes made by soheb

- index.html
Added some lines of code to indicate my message and where it starts and ends.
> Updated index.html with a message from Michelle

- index.html
I made my changes to the index.html page and added my message to make it serve as a public guest book.
> Added my message to the guestbook page

- index.html
I updated the files with my contribution to the guestbook.
> added my contribution

- index.html
Updated index.html with my message. I'm Daniel from Bolivia. Please accept me 😃
> added message from Daniel from Bolivia

- index.html
edited index.html with a quote
> edited index.html with a quote

- index.html
Edit index.html with my message (GODFrancySs). Now I'm excited to see it at Git Tutorial Guestbook
> Added GODFrancySs message

- index.html
Added thank you message to index.html
> Added thank you message to index.html

- index.html
added text to the index file and added h1 tag with some text to test
> new message is added by AadiiSk first time

- index.html
Left a nice message for w3schools and all coders out there.
> Added my message to show appreciation to W3schools.

- index.html
Thank you team w3schools. You guys are the the best
> Updated index.html with a thank you message

- README.md
- index.html
Hi, 
I wrote a little message for w3schools in index.html (I put it also in README but removed it, sorry for the error ! Hope it will not create conflicts). 
Thanks a lot for the whole Git tutorial. 
Best
> Little message

- index.html
Inserted my message for the tutorial guestbook.
> Update index.html tutorial guestbook

- index.html
I added a message to the guestbook following the guidelines at https://github.com/w3schools-test/w3schools-test.github.io/blob/master/README.md.
> Added line to guestbook

- index.html
Added my guest entry to the index.html file. Done as part of the [GitHub Send Pull Request](https://www.w3schools.com/git/git_remote_send_pull_request.asp?remote=github#:~:text=Git%20GitHub%20Send,Next%20%E2%9D%AF) to be found at [Git Tutorial](https://www.w3schools.com/git/default.asp?remote=github) site.
> Adding my guest entry for inclusion in the index.html/Guest book.

- index.html
> Update index.html by Prashant Soni added 1 Div

- index.html
I'm learning how to use GIHUB and I hope I've done it right. Once again I thank you for the tutorial.
> Feat: FFR modified index.html to add a msg to W3schools.

- index.html
I changed the index.html. Add explanations about git tutorial on w3schools.
> Changes the index.html

- index.html
Added a thank you message in index.html
> Git tutorial complete

- index.html
Thank you for the great tutorial! I also tried to resolve divergent local & remote branches in the process.
> Message from XS

- index.html
Thank you Again w3schools team! please approve my changes, I just wrote a simple message.
> I wrote my message

- index.html
> Add comment from David

- index.html
I added and updated files to make this serve as a public guestbook.
> changed to serve as a public guest book

- index.html
> Commiting blueAndWhite's message

- index.html
just a thank you note for such awesome content for free. helped me a lot
> Hritick Mallick , india

- index.html
Just added my name on index.html. Taking this great Git/GitHub tutorial. **Thank you W3Schools**!!! Bonne journée à tous! Auf wiedersehen!
> Hello from fjorg58, Ontario, Canada

- index.html
I've inserted a new paragraph to the index.html and post my message for the team.
> I've included my message to the team.

- index.html
Added an HTML text to your repo. please approve the pull request!
> Commit added by Kedar, India

- index.html
You're doing good. Keep moving.
> I just have added a sentence

- index.html
> Leave a message for w3schools in index.html

- index.html
I have added a div that contains my opinions about the git course on w3schools
> Added my opinion

- index.html
Hi. I hope you are well. I modified the index.html file by adding a few lines of code. Regards.
> Updated index.html. Greetings

- index.html
I added a message thanking w3schools for the knowledge it has given me since I first discovered it.
> Added message for the w3schools community

- index.html
I've added some new message in the body section for learning purpose and to thank you to W3 school for their hard work and dedication to teaching,
> added thank you message from Bangladesh

- index.html
feat: add message to index.html
> my message

- index.html
Hi W3Schools.
I just updated the index.html file, adding my message to the signature book. Please accept my changes to make them public.
> Added my own message

- index.html
> I have added new code ONKAR KADAM

- index.html
I just added new line to index.html .
> My first Pull request in this public GitHub repo.

- index.html
This is as suggested on the GitHub [tutorial at your webpage](https://www.w3schools.com/git/git_remote_fork.asp?remote=github).
> Add dense_set's message

- index.html
se agrego un div para especificar el nombre de donde se realiza el curso de git
> cambios en een el repositorio

- index.html
I have added my own contribution to the W3Schools Git Tutorial Guestbook with a div containing very simple styling.
> Added guestbook contribution from Andres Hung

- index.html
Thank you for making an easy content to learn programming.
> Adding a Nice thoughts for practicing

- index.html
Added my thanks note to w3schools for providing us with helpful resources to help us achieve our dreams.
> Added a thanks note to w3schools.

- index.html
> Comment by EfstathiosBilias

- index.html
I have added my message to the guestbook in index.html
> message added to guestbook

- index.html
I added, removed, and modified the file to serve as a public guest book.
> Add My Changes

- index.html
I modified the HTML. I added a div where I put a message saying hello ✌️
> Sending greetings to test the fork option in GitHub

- index.html
> added message from jaliprandi

- index.html
Added a Thank You message as indicated in Git tutorial on W3Schools.
> Added thank you message from Vivek Pandey

- index.html
I added my thanks in the end of index.html
> added my thanks

- index.html
I added my message to index.html.
> Adding my message.

- index.html
…hor link
Add id in class to call
> :ok_hand: chore(Update index.html) - Added an id to be called via anchor link

- index.html
I added a message to index.html. Bye!
> Added a message!

- index.html
> test contribution by pull request

- .vscode/settings.json
- index.html
Updated index.html with a new line about Git and Github tutorial on w3schools.
> Updated index.html with a new line.

- index.html
I just left a small thank you note.
> Just a small change

- index.html
added greetings from france in index.html
> added greetings from france in index.html

- index.html
> Added to guestbook

- index.html
> A small contribution

- index.html
Added a public guest book entry.
> Added entry to index.html

- index.html
I added comments in index.html.
> added message from tokyo

- index.html
> add a message in index.html

- index.html
I made a appreciated box due to following tutorial.
> My Text added

- index.html
> Add message thank W3school

- index.html
> added my thanks note

- index.html
> cooment added

- index.html
Added message from Diana, 
added some missing "!" for comments, which were forgotten to be placed by others.
> Added message from Diana

- index.html
I added my message to the index.html for your approval.
> Leave message to guestbook

- index.html
Added words of thanks, as changes for the study Fork
> index.html updates

- index.html
> Commit the changes

- index.html
> Hello from Uzbekistan

- index.html
Following the instructions on w3school on pushing changes to a forked gitHub
> added my greetings on line 76 to line 80

- index.html
placed my <div> in the html file and greetings. Thank you
> added my greetings on the html file.

- index.html
I added a line of text, expressing my gratitude for making my first push this week from git to github
> federick added line of text

- index.html
Nothing to say, W3Schools is awesome <3
> I add my div tag, with a lovely message, thanks u guys
